[package]
name = "calendar-to-csv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.25"
gcal = "0.1.6"
tokio = { version = "1.35", features = ["rt-multi-thread", "time"] }
